import { supabase, isSupabaseConfigured } from './lib/supabase';

const getEl=(id:string):any=>document.getElementById(id);
const domQuery=(selector:string):any=>document.querySelector(selector);
const domQueryAll=(selector:string):any[]=>Array.from(document.querySelectorAll(selector));
const courierStart={lat:18.4865,lng:-69.9640};
    const defaultStops:any[]=[
      {id:'1254',client:'María González',phone:'18095550125',address:'Calle Euclides Morillo 18, Los Prados',product:'Caja de cosméticos',quantity:1,unitPrice:1250,delivery:250,lat:18.4842,lng:-69.9510},
      {id:'1255',client:'Jean Pierre',phone:'18095550126',address:'Av. España 128, Alma Rosa',product:'Zapatos deportivos',quantity:1,unitPrice:1800,delivery:300,lat:18.4900,lng:-69.8580},
      {id:'1256',client:'Farmacia Viamont',phone:'18095550127',address:'Av. Isabel Aguiar 98, Herrera',product:'Vitaminas',quantity:2,unitPrice:950,delivery:250,lat:18.4540,lng:-69.9660}
    ];
    const savedOrders=(()=>{try{const rows=JSON.parse(localStorage.getItem('rutard_orders'));return Array.isArray(rows)?rows:[]}catch{return []}})();
    const assignedStops=savedOrders.filter(order=>order.courier==='Juan Martínez'&&!['Entregado','Cancelado','No entregado'].includes(order.status)).map(order=>{const sample=defaultStops.find(stop=>stop.id===String(order.id));return{id:String(order.id),client:order.name,phone:(order.phone||'').replace(/\D/g,'')||'18095550125',address:order.address||'Dirección pendiente',product:order.product||'Producto no especificado',quantity:Number(order.quantity)||1,unitPrice:Number(order.unitPrice)||0,delivery:Number(order.deliveryFee)||0,lat:sample?.lat||null,lng:sample?.lng||null,location:sample?`${sample.lat},${sample.lng}`:order.address||'Santo Domingo, República Dominicana'}});
    let availableStops:any[]=isSupabaseConfigured?assignedStops:assignedStops.length?assignedStops:defaultStops;
    let routeStops=(()=>{try{const ids=JSON.parse(localStorage.getItem('rutard_courier_route'));return Array.isArray(ids)?ids.map(id=>availableStops.find(stop=>stop.id===String(id))).filter(Boolean).concat(availableStops.filter(stop=>!ids.includes(stop.id))):availableStops}catch{return availableStops}})();
    function escapeHTML(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
    function money(value){return `RD$${Number(value).toLocaleString('es-DO')}`}
    function saveRoute(){try{localStorage.setItem('rutard_courier_route',JSON.stringify(routeStops.map(stop=>stop.id)))}catch{}}
    function drawRoute(){const destinations=routeStops.map(stop=>stop.location||`${stop.lat},${stop.lng}`).filter(Boolean);if(!destinations.length){getEl('courierMap').src='https://maps.google.com/maps?q=Santo%20Domingo%2C%20Rep%C3%BAblica%20Dominicana&z=12&hl=es&output=embed';return}const daddr=destinations.map(encodeURIComponent).join('+to:');getEl('courierMap').src=`https://maps.google.com/maps?saddr=${courierStart.lat}%2C${courierStart.lng}&daddr=${daddr}&dirflg=d&hl=es&output=embed`}
    function renderStops(){getEl('routeStops').innerHTML=routeStops.map((stop,index)=>{const destination=encodeURIComponent(stop.location||`${stop.lat},${stop.lng}`),waze=stop.lat&&stop.lng?`https://waze.com/ul?ll=${stop.lat}%2C${stop.lng}&navigate=yes`:`https://waze.com/ul?q=${destination}&navigate=yes`,trackingUrl=`https://rutard-logistica.bidojbcell.chatgpt.site/seguimiento/?token=${encodeURIComponent(stop.trackingToken||stop.id)}`,trackingMessage=encodeURIComponent(`Hola ${stop.client}, puedes darle seguimiento a tu pedido #${stop.id} aquí: ${trackingUrl}`);return`<article class="stop"><div class="stop-head"><b>${index+1}. ${escapeHTML(stop.client)} · #${escapeHTML(stop.id)}</b><button class="btn small" aria-label="Mover ${escapeHTML(stop.client)} hacia arriba" onclick="moveStop(${index},-1)" ${index===0?'disabled':''}>↑</button><button class="btn small" aria-label="Mover ${escapeHTML(stop.client)} hacia abajo" onclick="moveStop(${index},1)" ${index===routeStops.length-1?'disabled':''}>↓</button></div><p>${escapeHTML(stop.address)}<br><strong>WhatsApp:</strong> ${escapeHTML(stop.phone)}<br><strong>Producto:</strong> ${escapeHTML(stop.product)} × ${stop.quantity} · ${money(stop.unitPrice)} c/u<br><strong>Delivery:</strong> ${money(stop.delivery)}</p><div class="actions"><a class="btn primary" href="https://wa.me/${stop.phone}?text=${trackingMessage}" target="_blank" rel="noopener">Enviar link de seguimiento por WhatsApp</a><a class="btn whatsapp" href="https://wa.me/${stop.phone}?text=${encodeURIComponent(`Hola ${stop.client}, voy hacia tu dirección con el pedido #${stop.id}.`)}" target="_blank" rel="noopener">WhatsApp cliente</a><a class="btn" href="tel:+${stop.phone}">Llamar</a><a class="btn" href="https://www.google.com/maps/dir/?api=1&destination=${destination}" target="_blank" rel="noopener">Google Maps</a><a class="btn" href="${waze}" target="_blank" rel="noopener">Waze</a></div></article>`}).join('');drawRoute()}
    function moveStop(index,direction){const destination=index+direction;if(destination<0||destination>=routeStops.length)return;[routeStops[index],routeStops[destination]]=[routeStops[destination],routeStops[index]];saveRoute();renderStops()}
    function distance(a,b){const rad=value=>value*Math.PI/180,lat=rad(b.lat-a.lat),lng=rad(b.lng-a.lng),x=Math.sin(lat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(lng/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
    function sortNearest(){const remaining=[...routeStops],sorted=[];let from=courierStart;while(remaining.length){let index=0;for(let i=1;i<remaining.length;i++){const candidate=remaining[i].lat?distance(from,remaining[i]):Infinity,current=remaining[index].lat?distance(from,remaining[index]):Infinity;if(candidate<current)index=i}const [next]=remaining.splice(index,1);sorted.push(next);if(next.lat)from=next}routeStops=sorted;saveRoute();renderStops()}
    function resetRoute(){routeStops=[...availableStops];saveRoute();renderStops()}
    export async function hydrateCourierData(){if(!supabase)return;const{data:{user},error:userError}=await supabase.auth.getUser();if(userError)throw userError;if(!user)return;const{data,error}=await supabase.from('orders').select('*').eq('courier_id',user.id).order('created_at');if(error)throw error;availableStops=(data||[]).filter(order=>!['Entregado','Cancelado','No entregado'].includes(order.status)).map(order=>({id:String(order.id),trackingToken:order.tracking_token,client:order.customer_name,phone:String(order.customer_phone||'').replace(/\D/g,'')||'',address:order.address,product:order.product_name||'Producto no especificado',quantity:Number(order.quantity)||1,unitPrice:Number(order.unit_price)||0,delivery:Number(order.delivery_fee)||0,lat:null,lng:null,location:order.address||'Santo Domingo, República Dominicana'}));const ids=(()=>{try{return JSON.parse(localStorage.getItem('rutard_courier_route'))||[]}catch{return[]}})();routeStops=ids.length?ids.map(id=>availableStops.find(stop=>stop.id===String(id))).filter(Boolean).concat(availableStops.filter(stop=>!ids.includes(stop.id))):[...availableStops];saveRoute();renderStops();startLocationBroadcast(user.id)}
    let locationWatchId:number|undefined,lastLocationWrite=0;
    function startLocationBroadcast(courierId:string){if(!navigator.geolocation||locationWatchId!==undefined)return;locationWatchId=navigator.geolocation.watchPosition(position=>{const now=Date.now();if(now-lastLocationWrite<15000)return;lastLocationWrite=now;void supabase?.from('courier_locations').upsert({courier_id:courierId,latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy_meters:position.coords.accuracy,recorded_at:new Date(position.timestamp).toISOString()},{onConflict:'courier_id'}).then(({error})=>{if(error)console.error('No se pudo compartir la ubicación',error)})},error=>console.warn('Ubicación no disponible:',error.message),{enableHighAccuracy:true,maximumAge:10000,timeout:20000})}
    renderStops();

Object.assign(window, { sortNearest, resetRoute, moveStop });


export {};
