-- RutaRD core schema: courier accounts are created as pending by default.
-- No client-provided user metadata is trusted for role or approval status.

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text not null default '',
  role text not null default 'courier' check (role in ('admin', 'courier')),
  approval_status text not null default 'pending' check (approval_status in ('pending', 'approved', 'rejected')),
  approved_at timestamptz,
  approved_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.delivery_zones (
  id text primary key,
  name text not null,
  zone_type text not null check (zone_type in ('Provincia', 'Municipio', 'Sector')),
  province text not null,
  municipality text not null,
  delivery_fee numeric(12, 2) not null default 0 check (delivery_fee >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id text primary key default gen_random_uuid()::text,
  name text not null,
  default_price numeric(12, 2) not null default 0 check (default_price >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  tracking_token uuid not null unique default gen_random_uuid(),
  customer_name text not null,
  customer_phone text not null default '',
  address text not null,
  map_link text not null default '',
  product_id text references public.products(id) on delete set null,
  product_name text not null default '',
  quantity integer not null default 1 check (quantity > 0),
  unit_price numeric(12, 2) not null default 0 check (unit_price >= 0),
  zone_id text references public.delivery_zones(id) on delete set null,
  zone_name text not null default '',
  delivery_fee numeric(12, 2) not null default 0 check (delivery_fee >= 0),
  total numeric(12, 2) generated always as (quantity * unit_price + delivery_fee) stored,
  courier_id uuid references public.profiles(id) on delete set null,
  courier_name text not null default 'Sin asignar',
  status text not null default 'Pendiente' check (status in ('Pendiente', 'Asignado', 'En camino', 'Llegando', 'Entregado', 'No entregado', 'Cancelado')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.courier_locations (
  courier_id uuid primary key references public.profiles(id) on delete cascade,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  accuracy_meters double precision,
  recorded_at timestamptz not null default now()
);

create index orders_courier_status_created_idx on public.orders (courier_id, status, created_at desc);
create index orders_created_at_idx on public.orders (created_at desc);
create index products_active_name_idx on public.products (is_active, name);
create index delivery_zones_active_name_idx on public.delivery_zones (is_active, name);
create index courier_locations_recorded_at_idx on public.courier_locations (recorded_at desc);

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated;

create function private.is_approved_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.role = 'admin'
      and p.approval_status = 'approved'
  );
$$;
revoke all on function private.is_approved_admin() from public, anon;
grant execute on function private.is_approved_admin() to authenticated;

create function private.is_approved_courier()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.role = 'courier'
      and p.approval_status = 'approved'
  );
$$;
revoke all on function private.is_approved_courier() from public, anon;
grant execute on function private.is_approved_courier() to authenticated;

create function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', '')
  );
  return new;
end;
$$;
revoke all on function private.handle_new_user() from public, anon, authenticated;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();

alter table public.profiles enable row level security;
alter table public.delivery_zones enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.courier_locations enable row level security;

grant select, update (full_name, phone) on public.profiles to authenticated;
grant select, insert, update, delete on public.delivery_zones to authenticated;
grant select, insert, update, delete on public.products to authenticated;
grant select, insert, delete, update (status) on public.orders to authenticated;
grant select, insert, update, delete on public.courier_locations to authenticated;

create policy "Users can read their own profile; admins can read all profiles"
  on public.profiles for select to authenticated
  using ((select auth.uid()) = id or (select private.is_approved_admin()));
create policy "Users can update their own contact details"
  on public.profiles for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy "Authenticated users can view active delivery zones"
  on public.delivery_zones for select to authenticated
  using ((select private.is_approved_courier()) and is_active or (select private.is_approved_admin()));
create policy "Admins manage delivery zones"
  on public.delivery_zones for all to authenticated
  using ((select private.is_approved_admin()))
  with check ((select private.is_approved_admin()));

create policy "Authenticated users can view active products"
  on public.products for select to authenticated
  using ((select private.is_approved_courier()) and is_active or (select private.is_approved_admin()));
create policy "Admins manage products"
  on public.products for all to authenticated
  using ((select private.is_approved_admin()))
  with check ((select private.is_approved_admin()));

create policy "Admins can view every order and couriers only their assigned orders"
  on public.orders for select to authenticated
  using ((select private.is_approved_admin()) or ((select private.is_approved_courier()) and courier_id = (select auth.uid())));
create policy "Admins can create orders"
  on public.orders for insert to authenticated
  with check ((select private.is_approved_admin()));
create policy "Admins can delete orders"
  on public.orders for delete to authenticated
  using ((select private.is_approved_admin()));
create policy "Admins and assigned couriers can update order status"
  on public.orders for update to authenticated
  using ((select private.is_approved_admin()) or ((select private.is_approved_courier()) and courier_id = (select auth.uid())))
  with check ((select private.is_approved_admin()) or ((select private.is_approved_courier()) and courier_id = (select auth.uid())));

create policy "Admins can view all courier locations and couriers their own"
  on public.courier_locations for select to authenticated
  using ((select private.is_approved_admin()) or courier_id = (select auth.uid()));
create policy "Couriers can publish only their own location"
  on public.courier_locations for insert to authenticated
  with check ((select private.is_approved_courier()) and courier_id = (select auth.uid()));
create policy "Couriers can update only their own location"
  on public.courier_locations for update to authenticated
  using ((select private.is_approved_courier()) and courier_id = (select auth.uid()))
  with check ((select private.is_approved_courier()) and courier_id = (select auth.uid()));
create policy "Admins can delete courier locations"
  on public.courier_locations for delete to authenticated
  using ((select private.is_approved_admin()));

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'courier_locations'
     ) then
    alter publication supabase_realtime add table public.courier_locations;
  end if;
end;
$$;

create function public.approve_courier(p_courier_id uuid, p_approve boolean)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not (select private.is_approved_admin()) then
    raise exception 'Only an approved administrator can approve couriers';
  end if;

  update public.profiles
  set approval_status = case when p_approve then 'approved' else 'rejected' end,
      approved_at = case when p_approve then now() else null end,
      approved_by = (select auth.uid()),
      updated_at = now()
  where id = p_courier_id and role = 'courier';

  if not found then
    raise exception 'Courier account was not found';
  end if;
end;
$$;
revoke all on function public.approve_courier(uuid, boolean) from public, anon;
grant execute on function public.approve_courier(uuid, boolean) to authenticated;

create function public.assign_order(p_order_id bigint, p_courier_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not (select private.is_approved_admin()) then
    raise exception 'Only an approved administrator can assign orders';
  end if;

  if not exists (
    select 1 from public.profiles p
    where p.id = p_courier_id and p.role = 'courier' and p.approval_status = 'approved'
  ) then
    raise exception 'Courier must be approved before receiving orders';
  end if;

  update public.orders
  set courier_id = p_courier_id,
      status = case when status = 'Pendiente' then 'Asignado' else status end,
      updated_at = now()
  where id = p_order_id;

  if not found then
    raise exception 'Order was not found';
  end if;
end;
$$;
revoke all on function public.assign_order(bigint, uuid) from public, anon;
grant execute on function public.assign_order(bigint, uuid) to authenticated;

create function public.get_tracking_info(p_tracking_token uuid)
returns table (
  order_id bigint,
  customer_name text,
  address text,
  status text,
  product_name text,
  quantity integer,
  courier_name text,
  courier_phone text,
  courier_latitude double precision,
  courier_longitude double precision,
  location_recorded_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select o.id, o.customer_name, o.address, o.status, o.product_name, o.quantity,
         p.full_name, p.phone, cl.latitude, cl.longitude, cl.recorded_at
  from public.orders o
  left join public.profiles p on p.id = o.courier_id
  left join public.courier_locations cl on cl.courier_id = o.courier_id
  where o.tracking_token = p_tracking_token;
$$;
revoke all on function public.get_tracking_info(uuid) from public;
grant execute on function public.get_tracking_info(uuid) to anon, authenticated;

alter table public.profiles add constraint profiles_approved_by_admin_only
  check ((role = 'admin' and approval_status = 'approved' and approved_at is not null)
      or (approval_status = 'pending' and approved_at is null and approved_by is null)
      or (approval_status = 'rejected' and approved_by is not null)
      or (approval_status = 'approved' and approved_at is not null and approved_by is not null));
